name: thai_buddhist_date_app
description: Demo and integration app for Thai Buddhist date packages.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  thai_buddhist_date:
    path: packages/thai_buddhist_date
  thai_buddhist_date_pickers:
    path: packages/thai_buddhist_date_pickers

dependency_overrides:
  thai_buddhist_date:
    path: packages/thai_buddhist_date

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
