name: Publish to pub.dev

on:
  push:
    tags:
      - "thai_buddhist_date-v[0-9]+.[0-9]+.[0-9]+"
      - "thai_buddhist_date_pickers-v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-core:
    name: Publish thai_buddhist_date
    if: startsWith(github.ref_name, 'thai_buddhist_date-v')
    permissions:
      contents: read
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@65eb853c7ba17dde3be364c3d2858773e7144260
    with:
      working-directory: packages/thai_buddhist_date
      environment: pub.dev

  publish-pickers:
    name: Publish thai_buddhist_date_pickers
    if: startsWith(github.ref_name, 'thai_buddhist_date_pickers-v')
    permissions:
      contents: read
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@65eb853c7ba17dde3be364c3d2858773e7144260
    with:
      working-directory: packages/thai_buddhist_date_pickers
      environment: pub.dev
