name: thai_buddhist_date_pickers
description: Flutter calendar and pickers (dialog/fullscreen, range, multi) for Thai Buddhist (พ.ศ.) and Gregorian (ค.ศ.), built on thai_buddhist_date.
version: 0.1.1
repository: https://github.com/Kidpech-code/thai_buddhist_date
issue_tracker: https://github.com/Kidpech-code/thai_buddhist_date/issues
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"
dependencies:
  flutter:
    sdk: flutter
  thai_buddhist_date: ^0.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
